version: '2'
services:
    sbg_manager-app:
        image: sbg_manager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sbg_manager-postgresql:5432/sbg_manager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sbg_manager-postgresql:
        extends:
            file: postgresql.yml
            service: sbg_manager-postgresql
